---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: "{{ project_name }}"
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      targetPort: 6379
      name: redis-6379
      port: 6379
