---
- hosts: all
  become: true
  tasks:
    - name: 'Check if firewalld is running'
      command: systemctl status firewalld
      register: firewalld_status
      ignore_errors: true

    - block:
        - name: 'Check for dockerc firewall zone'
          command: 'firewall-cmd --permanent --get-zones'
          register: firewall_zones

        - name: 'Add dockerc firewall zone'
          command: 'firewall-cmd --permanent --new-zone dockerc'
          when: "'dockerc' not in firewall_zones.stdout"

        - name: 'Add dockerc firewall configs'
          command: "{{ item }}"
          with_items:
            - firewall-cmd --permanent --zone dockerc --add-source 172.17.0.0/16
            - firewall-cmd --permanent --zone dockerc --add-port 8443/tcp
            - firewall-cmd --permanent --zone dockerc --add-port 53/udp
            - firewall-cmd --permanent --zone dockerc --add-port 8053/udp

        - name: 'Reload firewall'
          command: firewall-cmd --reload
      when: firewalld_status | success

- hosts: all
  become: true
  roles:
    - epel_repositories
  tasks:
    - name: 'Install docker'
      yum:
        name: docker
        state: present

    - name: 'Configure insecure registry'
      lineinfile:
        dest: /etc/sysconfig/docker
        line: INSECURE_REGISTRY='--insecure-registry 172.30.0.0/16'
        regexp: "^INSECURE_REGISTRY"
      notify:
        - 'Restart docker'
  handlers:
    - name: 'Restart docker'
      service:
        name: docker
        state: restarted

- hosts: all
  become: true
  tasks:
    - name: 'Replace Apache SSL config with Proxy'
      template:
        src: containers/templates/05-foreman-ssl.conf
        dest: /etc/httpd/conf.d/05-foreman-ssl.conf
        owner: apache
        group: apache

    - name: 'Restart Apache'
      command: 'systemctl restart httpd'

- hosts: all
  become: true
  tasks:
    - name: Ensure postgresql can listen on all addresses
      lineinfile:
        path: /var/lib/pgsql/data/postgresql.conf
        regexp: ^listen_addresses
        line: listen_addresses = '*'

- hosts: all
  become: true
  tasks:
    - name: Get postgres password
      slurp:
        src: /etc/foreman/database.yml
      register: database_file

    - set_fact:
        postgres_password: "{{ database_file['content'] | b64decode | from_yaml }}"

    - debug:
        msg: "{{ postgres_password }}"

    - set_fact:
        postgres_password: "{{ postgres_password['production']['password'] }}"

    - name: Foreman systemd file
      template:
        src: containers/templates/foreman.service
        dest: /etc/systemd/system/foreman.service

    - name: Restart Foreman service
      command: systemctl restart foreman
