---
- hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - secrets.yml
  environment:
    K8S_AUTH_HOST: "https://{{ lookup('env', 'KUBERNETES_SERVICE_HOST') }}"
    K8S_AUTH_API_KEY: "{{ lookup('file', '/var/run/secrets/kubernetes.io/serviceaccount/token') }}"
    K8S_AUTH_SSL_CA_CERT: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  tasks:
    - set_fact:
        project_name: "{{ lookup('file', '/var/run/secrets/kubernetes.io/serviceaccount/namespace') }}"

    - import_tasks: deploy/secrets.yml
