---
- hosts: localhost
  gather_facts: no
  tasks:
    - set_fact:
        postgres_port: "{{ lookup('env', 'POSTGRES_SERVICE_PORT') | int }}"
        postgres_host: "{{ lookup('env', 'POSTGRES_SERVICE_HOST') }}"

    - name: "wait for postgres port"
      wait_for:
        port: "{{ postgres_port }}"
        host: "{{ postgres_host }}"
        timeout: 10
