---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: foreman
  namespace: "{{ project_name }}"
  labels:
    app: foreman
    service: foreman
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: foreman
        service: foreman
    spec:
      containers:
        - name: foreman
          securityContext: {}
          state: present
          volumeMounts:
            - readOnly: true
              mountPath: /etc/pki/katello/private
              name: keys
            - readOnly: true
              mountPath: /etc/pki/katello/certs
              name: certs
          env:
            - name: POSTGRES_DB
              value: foreman
            - name: POSTGRES_USER
              value: foreman
            - name: POSTGRES_PASSWORD
              value: foreman
            - name: SEED_ADMIN_USER
              value: admin
            - name: SEED_ADMIN_PASSWORD
              value: changeme
            - name: RAILS_ENV
              value: production
          ports:
            - protocol: TCP
              containerPort: 8080
          image: "172.30.1.1:5000/foreman/foreman:latest"
      serviceAccount: anyuid
      serviceAccountName: anyuid
      volumes:
        - secret:
            items:
              - path: ca.key
                key: ca.key
              - path: pulp-client.key
                key: pulp-client.key
            secretName: keys
          name: keys
        - secret:
            items:
              - path: ca.crt
                key: ca.crt
              - path: pulp-client.crt
                key: pulp-client.crt
            secretName: certs
          name: certs
  strategy:
    type: Rolling
    rollingParams:
      timeoutSeconds: 900
