---
- name: Deploy Candlepin
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    minishift: true
    cluster_up: false
    registry: quay.io/foreman
    project_name: candlepin
    deployment_state: present
  pre_tasks:
    - set_fact:
        project_name: "{{ project_name | default('foreman') }}"

    #- set_fact:
    #    postgres_user: "{{ candlepin_database_user }}"
    #    postgres_database: "{{ candlepin_database_user }}"
    #    postgres_password: "{{ candlepin_database_password }}"

    - set_fact:
        application_hostname: "{{ application_hostname | default('') }}"
    - shell: minishift ip
      register: minishift_ip
      when: minishift == true
    - set_fact:
        application_hostname: "foreman.{{ minishift_ip.stdout }}.nip.io"
      when: application_hostname == '' and minishift == true and cluster_up == false
    - set_fact:
        application_hostname: "foreman.{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}.nip.io"
      when: application_hostname == '' and cluster_up == true and minishift == false
  roles:
    - project
    - service-accounts
    - candlepin
