---
apiVersion: v1
kind: Secret
metadata:
  name: candlepin-conf
  namespace: "{{ project_name }}"
type: Opaque
data:
  candlepin.conf: "{{ lookup('template', 'templates/candlepin.conf') | b64encode }}"
  candlepin_database_password: "{{ candlepin_database_password | b64encode }}"
