---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: candlepin
  namespace: "{{ project_name }}"
  labels:
    app: candlepin
spec:
  replicas: "{{ replica_count }}"
  strategy:
    type: Rolling
    rollingParams:
      timeoutSeconds: 900
  template:
    metadata:
      labels:
        app: candlepin
    spec:
      serviceAccount: anyuid
      serviceAccountName: anyuid
      containers:
        - name: candlepin
          image: "172.30.1.1:5000/candlepin/candlepin:latest"
          state: present
          volumeMounts:
            - name: ca
              mountPath: /etc/candlepin/certs
              readOnly: true
            - name: candlepin-conf
              mountPath: /etc/candlepin
              readOnly: true
          env:
            - name: POSTGRES_DATABASE
              value: "{{ candlepin_database }}"
            - name: POSTGRES_USER
              value: "{{ candlepin_database_user }}"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: candlepin-conf
                  key: candlepinDatabasePassword
          livenessProbe:
            httpGet:
              path: /candlepin/status
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /candlepin/status
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: ca
          secret:
            secretName: ca
            items:
              - path: candlepin-ca.key
                key: ca.key
              - path: candlepin-ca.crt
                key: ca.crt
        - name: candlepin-conf
          secret:
            secretName: candlepin-conf
            items:
              - key: candlepin.conf
                path: candlepin.conf

