---
- name: project foreman
  openshift_raw:
    state: present
    definition:
      apiVersion: project.openshift.io/v1
      kind: Project
      metadata:
        name: "{{ project_name }}"
        annotations:
          openshift.io/display-name: Foreman
          openshift.io/description: Foreman stack
