---
- name: foreman persistent volume claim
  k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.pvc.yaml') | from_yaml }}"
  with_items:
    - pub-data

- name: foreman jobs
  k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.job.yaml') | from_yaml }}"
  with_items:
    - certificates

- name: foreman service
  k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.service.yaml') | from_yaml }}"
  with_items:
    - foreman
    - memcached

- name: foreman deployment
  k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.deployment.yaml') | from_yaml }}"
  with_items:
    - foreman
    - dynflow
    - memcached

- name: foreman routes
  k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.route.yaml') | from_yaml }}"
  with_items:
    - foreman-https
    - foreman-http-pub
    - foreman-http-pulp
