---
- name: foreman config maps
  k8s_raw:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.config-map.yaml') | from_yaml }}"
  with_items:
    - httpd

- name: foreman service
  k8s_raw:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.service.yaml') | from_yaml }}"
  with_items:
    - foreman
    - httpd
    - memcached

- name: foreman deployment
  openshift_raw:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.deployment.yaml') | from_yaml }}"
  with_items:
    - foreman
    - dynflow
    - memcached
    - httpd

- name: foreman routes
  openshift_raw:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.route.yaml') | from_yaml }}"
  with_items:
    - foreman-https
    - foreman-http-pub
    - foreman-http-pulp
