---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: "{{ project_name }}"
  labels:
    app: postgres
spec:
  type: LoadBalancer
  selector:
    app: postgres
  ports:
    - protocol: TCP
      targetPort: 5432
      name: postgres
      port: 5432
