---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: postgres
  namespace: "{{ project_name }}"
  labels:
    app: postgres
spec:
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          env:
            - name: POSTGRES_DB
              value: foreman
            - name: POSTGRES_USER
              value: foreman
            - name: POSTGRES_PASS
              value: foreman
            - name: PGDATA
              value: /var/lib/pgsql/data/userdata
          volumeMounts:
            - readOnly: false
              mountPath: /var/lib/pgsql/data
              name: postgres-data
          image: ansible/postgresql
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
  replicas: 1
  strategy:
    type: Rolling
    rollingParams:
      timeoutSeconds: 900
