---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: postgres
  namespace: "{{ project_name }}"
  labels:
    app: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: ansible/postgresql
          env:
            - name: POSTGRES_DB
              value: "{{ postgres_database }}"
            - name: POSTGRES_USER
              value: "{{ postgres_user }}"
            - name: POSTGRES_PASS
              value: "{{ postgres_password }}"
            - name: PGDATA
              value: /var/lib/pgsql/data/userdata
          volumeMounts:
            - readOnly: false
              mountPath: /var/lib/pgsql/data
              name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
