---
apiVersion: v1
kind: Service
metadata:
  name: httpd
  namespace: "{{ project_name }}"
  labels:
    app: httpd
spec:
  selector:
    app: httpd
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
