---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: httpd
  namespace: "{{ project_name }}"
  labels:
    app: httpd
spec:
  selector:
    name: httpd
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 1200
  triggers:
    - type: ConfigChange
  replicas: 1
  template:
    metadata:
      name: "httpd"
      labels:
        app: "httpd"
    spec:
      serviceAccount: anyuid
      serviceAccountName: anyuid
      containers:
        - name: httpd
          image: "manageiq/httpd:latest"
          command:
            - /usr/sbin/init
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: httpd-config
              mountPath: "/etc/httpd/conf.d"
            - name: keys
              mountPath: /etc/pki/katello/private
              readOnly: true
            - name: certs
              mountPath: /etc/pki/katello/certs
              readOnly: true
          lifecycle:
            postStart:
              exec:
                command:
                  - "/usr/bin/save-container-environment"
      volumes:
        - name: httpd-config
          configMap:
            name: "httpd-configs"
        - name: certs
          secret:
            secretName: certs
            items:
              - path: katello-default-ca.crt
                key: ca.crt
              - path: server.crt
                key: server.crt
        - name: keys
          secret:
            secretName: keys
            items:
              - path: server.key
                key: server.key
