---
- hosts: all
  gather_facts: no
  tasks:
    - name: 'Install ruby'
      yum:
        name: ruby
        state: present

    - name: 'Run tests'
      shell: ./test/test.rb
      args:
        chdir: "{{ working_dir }}"
