---
apiVersion: v1
kind: Service
metadata:
  name: pulp-core
  namespace: "{{ project_name }}"
  labels:
    app: pulp-core
spec:
  selector:
    app: pulp-core
  ports:
    - protocol: TCP
      targetPort: 8080
      name: pulp-core-8080
      port: 8080
