---
- hosts: localhost
  vars:
    host_data: "{{ lookup('file', './host_data.json') | from_json }}"
    private_key: "~/.ssh/id_rsa"
  tasks:
    - name: Add requested nodes to hosts file
      add_host:
        name: "{{ item }}"
        groups: "nodes"
        ansible_fqdn: "{{ item }}"
        ansible_ssh_user: "root"
        ansible_ssh_private_key_file: "{{ private_key }}"
      with_items: "{{ host_data.hosts }}"

        #    - name: Setup custom facts directory
        #      file:
        #        state: "directory"
        #        recurse: "yes"
        #        path: "/etc/ansible/facts.d"
        #      delegate_to: "{{ item }}"
        #      with_items: "{{ groups['nodes'] }}"
        #
        #    - name: Install ci custom facts for provisioning traceability
        #      template:
        #        src: "templates/ci.fact.j2"
        #        dest: "/etc/ansible/facts.d/ci.fact"
        #      delegate_to: "{{ item }}"
        #      with_items: "{{ groups['nodes'] }}"
        #
        #    - name: Refresh facts
        #      setup:
        #        filter: "ansible_local"

- hosts: nodes
  vars:
    katello_version: nightly
    katello_foreman_version: nightly
    katello_installer_command: foreman-installer --scenario katello --foreman-admin-password "changeme"
    katello_use_koji: true
  roles:
    - foreman_repositories
    - katello_repositories
    - katello
