---
- set_fact:
    secret_key: "{{ lookup('password', '/dev/null length=50 chars=ascii_letters') }}"

- name: pulp-core config-map
  k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.config-map.yaml') | from_yaml }}"
  with_items:
    - pulp-core

- name: pulp-core service
  k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.service.yaml') | from_yaml }}"
  with_items:
    - pulp-core

- name: postges deployment
  k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.deployment.yaml') | from_yaml }}"
  with_items:
    - pulp-core
